spring:
  datasource:
    url: jdbc:h2:~/data/cat-toys  # jdbc는 스프링에서 DB를 템플릿 메소드를 써서 사용할 수 있도록 한다.리 h2: DB, ~: 홈 디렉토리. data폴더 안에 cat-tosy 폴더 안에 쓰여진다
  jpa:
    hibernate:
      ddl-auto: update  # DDL update
---
spring:
  profiles: test  # 환경변수 구분할 수 있다.
  datasource:
    url: jdbc:h2:mem:test # 테스트일 때는 메모리 사용
